import Head from 'next/head';
import Image from 'next/image';
import { useContext, useEffect } from 'react';
import styles from '../styles/Home.module.scss';
import { AppContext } from '../src/Providers/AppProvider';
import { LaunchList } from '../src/components/LaunchList';

// Example of using next/Image
// <Image src='https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png' alt='ss' width='200px' height='200px'/>

export default function Home() {
  const { isLoading, getLaunches } = useContext(AppContext);

  useEffect(() => {
    getLaunches(10);
  }, [getLaunches]);

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>{isLoading ? <span>is loading...</span> : <LaunchList />}</main>

      <footer className={styles.footer}>
        <a href='https://github.com/Dpartipilo' target='_blank' rel='noopener noreferrer'>
          Project made by Diego Partipilo
          <span className={styles.logo}>
            <Image src='/github.svg' alt='Github Logo' width={30} height={20} />
          </span>
        </a>
      </footer>
    </div>
  );
}
